### ISSUE TITLE
facing the issues with lambda function module

### ISSUE THREAD

**Issue by nistala** [plangdon/deeplens_birds#1]
hi,
Im working on DeepLens faced the issues with lambda i.e **Traceback (most recent call last):
  File "greengrassHelloWorld.py", line 9, in <module>
    import awscam
ModuleNotFoundError: No module named 'awscam'**

As I have tried many ways to import this module locally and on cloud by failed 

Can you please let me know how to resolve this issue 
Thank you 
Sai Kartik N
![lambda error](https://user-images.githubusercontent.com/42006773/53166743-2c228000-35fc-11e9-9f2b-35cc687fdb26.png)
istala

**Comment by plangdon** [comment]
This project was built using the beta of DeepLens. I have not tried to run it since it was launched. I will try to run it myself again and see if it resolves.

Thanks,

Paul

On Feb 21, 2019, at 6:44 AM, nistala <notifications@github.com> wrote:

hi,
Im working on DeepLens faced the issues with lambda i.e Traceback (most recent call last):
File "greengrassHelloWorld.py", line 9, in 
import awscam
ModuleNotFoundError: No module named 'awscam'

As I have tried many ways to import this module locally and on cloud by failed

Can you please let me know how to resolve this issue
Thank you
Sai Kartik N

istala

**Comment by nistala** [comment]
Thanks Paul, 

what is difference between Beta version and current versions. 

I just want to know is there any awscam module available locally installation. Because in device we have prebuilt dependency awscam folder which is not readable format 

Thank you 

Sai Kartik Nistala 
Research Associate - Cognitive 
Phone : (891)-769-6166 
Mobile : (891)-769-6166 
Email : snistala@miraclesoft.com 
		Miracle Heights - APAC HQ 
Hill No. 1, IT SEZ, Chinna Rushi Konda 
Visakhapatnam, AP - 530045, India 
www.miraclesoft.com
